import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Checkout } from '@/components';
import { CheckoutProvider } from '@/contexts/checkout';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${inter.className}`}>
        <div
          className="App"
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            height: '100vh', // Это гарантирует, что div занимает всю высоту экрана
          }}
        >
          <CheckoutProvider>
            <Checkout />
          </CheckoutProvider>
        </div>
      </main>
    </>
  )
}
